# Pre-commit hooks for ZeroTrust IAM Analyzer
# See https://pre-commit.com for more information

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: end-of-file-fixer
        name: Fix end of files
      - id: check-yaml
        name: Check YAML syntax
      - id: check-added-large-files
        name: Check for large files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-toml
        name: Check TOML syntax
      - id: check-json
        name: Check JSON syntax
        exclude: '.vscode/settings.json'

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        name: Format Python code with Black
        language_version: python3.13
        args: ['--line-length=100']

  # Python import sorting
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        name: Sort Python imports with isort
        args: ["--profile", "black", "--line-length=100"]

  # Python linting
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        name: Lint Python code with flake8
        args: ['--max-line-length=100', '--extend-ignore=E203,W503']

  # Python type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        name: Type check Python code with mypy
        additional_dependencies: []
        args: ['--ignore-missing-imports', '--check-untyped-defs']

  # Python security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        name: Scan Python code for security issues
        args: ['-c', 'pyproject.toml']
        additional_dependencies: ['bandit[toml]']
