"""add password reset fields to user model

Revision ID: fbe8b411d4e5
Revises: 7dbf784c6278
Create Date: 2025-10-25 23:02:42.438685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbe8b411d4e5'
down_revision: Union[str, None] = '7dbf784c6278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_reset_token', sa.String(length=255), nullable=True, comment='Password reset token'))
    op.add_column('user', sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when password reset token expires'))
    op.create_index(op.f('ix_user_password_reset_token'), 'user', ['password_reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_password_reset_token'), table_name='user')
    op.drop_column('user', 'password_reset_expires')
    op.drop_column('user', 'password_reset_token')
    # ### end Alembic commands ###
